apiVersion: v1
kind: Service
metadata:
  name: titan-website-service
  namespace: myapp
spec:
  selector:
    app: titan-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
